min_fit_clients: ${net.fl.clients_number}
min_available_clients: ${net.fl.clients_number}
min_evaluate_clients: 1
num_rounds: 50
fraction_fit: 1.0
fraction_evaluate: 0.0
server_eval: false
val_batch_size: 128
server_param_init: true
stop_by_accuracy: false
accuracy_level: 0.8
collect_metrics: true
# collect_metrics_interval: 30
