topology:
  source: "topohub"
  topohub_id: "gabriel/5/0"
  link_config: { }
  extra: { }

fl:
  clients_number: 20
  image: "fleet-fl:latest"
  network: "10.0.0.0/16"
  clients_limits:
    cpu: 1.0
    mem: 2048
    distribution: homogeneous
  server_limits:
    cpu: 1.0
    mem: 4096
  extra: 
    disable_gpu: true

bg:
  enabled: false
  image: "fleet-bg:latest"
  network: "10.1.0.0/16"
  extra: { }

sdn:
  sdn_enabled: false
  controller_ip: "localhost"
  controller_port: 6633
  controller_type: "openflow"
  extra: { }

